CREATE DATABASE IF NOT EXISTS CUSTOMER360;

CREATE SCHEMA IF NOT EXISTS CUSTOMER360.RAW;
CREATE SCHEMA IF NOT EXISTS CUSTOMER360.CLEAN;
CREATE SCHEMA IF NOT EXISTS CUSTOMER360.GOLD;

CREATE WAREHOUSE IF NOT EXISTS MY_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 30
AUTO_RESUME = TRUE;
