CREATE OR REPLACE TABLE CLEAN.CUSTOMERS AS
SELECT
    ID,
    YEAR_BIRTH,
    (2025 - YEAR_BIRTH) AS AGE,

    UPPER(EDUCATION) AS EDUCATION_CLEAN,
    UPPER(MARITAL_STATUS) AS MARITAL_STATUS_CLEAN,
    INCOME AS INCOME_CLEAN,

    KIDHOME,
    TEENHOME,
    DT_CUSTOMER,
    RECENCY,

    MNTWINES,
    MNTFRUITS,
    MNTMEATPRODUCTS,
    MNTFISHPRODUCTS,
    MNTSWEETPRODUCTS,
    MNTGOLDPRODS,

    NUMDEALSPURCHASES,
    NUMWEBPURCHASES,
    NUMCATALOGPURCHASES,
    NUMSTOREPURCHASES,
    NUMWEBVISITSMONTH,

    ACCEPTEDCMP3,
    ACCEPTEDCMP4,
    ACCEPTEDCMP5,
    ACCEPTEDCMP1,
    ACCEPTEDCMP2,

    COMPLAIN,
    Z_COSTCONTACT,
    Z_REVENUE,
    RESPONSE
FROM RAW.CUSTOMERS_RAW;
