CREATE OR REPLACE TABLE GOLD.CUSTOMER_360 AS
SELECT
    ID,
    YEAR_BIRTH,
    AGE,
    EDUCATION_CLEAN AS EDUCATION,
    MARITAL_STATUS_CLEAN AS MARITAL_STATUS,
    INCOME_CLEAN AS INCOME,

    (KIDHOME + TEENHOME) AS TOTAL_CHILDREN,

    (MNTWINES + MNTFRUITS + MNTMEATPRODUCTS +
     MNTFISHPRODUCTS + MNTSWEETPRODUCTS + MNTGOLDPRODS) AS TOTAL_SPENT,

    (NUMDEALSPURCHASES + NUMWEBPURCHASES +
     NUMCATALOGPURCHASES + NUMSTOREPURCHASES) AS TOTAL_PURCHASES,

    NUMWEBVISITSMONTH AS WEB_VISITS,

    RECENCY,
    RESPONSE AS CAMPAIGN_RESPONSE,

    DT_CUSTOMER
FROM CLEAN.CUSTOMERS;
