-- Top 10 high value customers
SELECT ID, TOTAL_SPENT
FROM GOLD.CUSTOMER_360
ORDER BY TOTAL_SPENT DESC
LIMIT 10;

-- High churn probability customers
SELECT *
FROM GOLD.CUSTOMER_PREDICTIONS
WHERE CHURN_PROBABILITY > 0.7
ORDER BY CHURN_PROBABILITY DESC;

-- Customer segmentation
SELECT EDUCATION, COUNT(*)
FROM GOLD.CUSTOMER_360
GROUP BY EDUCATION;
